dev/config/routes.rb
Rails.application.routes.draw do
  get 'user/index'

  get 'user/show'

  get 'user/new'

  get 'user/create'

  get 'user/edit'

  get 'user/update'

  resources :product,only: [:new,:create,:destroy]
  resources :item,only: [:create,:destroy]
  resources :users, only: [:index, :show, :create, :edit, :update]
  
  get 'signup', to: 'users#new'
  get 'trade/show'
  root 'top#main'
  get 'top/main'
  post 'top/login'
  get 'login/new'
  get 'trade/end'
  get 'top/error'
end

dev/app/models/item.rb
class Item < ActiveRecord::Base
end

dev/app/models/product.rb
class Product < ActiveRecord::Base
end

dev/app/models/trade.rb
class Trade < ActiveRecord::Base
end

dev/app/models/user.rb
class User < ActiveRecord::Base
     before_save { self.email.downcase! }
 
  validates :nickname, presence: true, length: { maximum: 50 }
 
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    private
 
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
end

dev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dev/app/controllers/item_controller.rb
class ItemController < ApplicationController
  def create
    logger.debug "ID:"
    logger.debug params[:id]
    item = Item.find_by(product_id: params[:id],trade_id: session[:trade_id])
    if item
      item.qty += 1
    else
      item = Item.new(qty:1,product_id: params[:id], trade_id: session[:trade_id])
    end
    item.save
    redirect_to trade_show_path
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to trade_show_path
  end
end

dev/app/controllers/product_controller.rb
class ProductController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(name: params[:product][:name],price: params[:product][:name])
    @product.save
    redirect_to top_main_path
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to top_main_path
  end
end

dev/app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid] then
            render "home"
        else
            render"login"
        end
    end
    def login
        user = User.find_by(uid: params[:uid],pass: params[:pass])
        if user then 
            session[:login_uid] = params[:uid]
            redirect_to "/"
        else 
            render "error"
        end
    end
    def logout
        session.delete(:login_uid)
        redirect_to "/"
    end
end

dev/app/controllers/trade_controller.rb
class TradeController < ApplicationController
  def show
    @item = Item.where(trade_id: session[:trade_id])
    @tal = 0 
  end
end

dev/app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
 
    if @user.save
      flash[:success] = '新規のユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
end

dev/app/helpers/application_helper.rb
module ApplicationHelper
end

dev/app/helpers/item_helper.rb
module ItemHelper
end

dev/app/helpers/product_helper.rb
module ProductHelper
end

dev/app/helpers/top_helper.rb
module TopHelper
end

dev/app/helpers/trade_helper.rb
module TradeHelper
end

dev/app/helpers/user_helper.rb
module UserHelper
end

dev/app/views/item/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

dev/app/views/item/destroy.html.erb
<h1>Item#destroy</h1>
<p>Find me in app/views/item/destroy.html.erb</p>

dev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dev/app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

dev/app/views/product/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

dev/app/views/product/new.html.erb
<%= form_for @product,:url => {:action => :create} do |f| %>

  <%= f.label :name,"商品名" %>
  <%= f.text_field :name %><br>
  
  <%= f.label :name,"欲しいもの" %>
  <%= f.text_field :price %><br>
  
  <%= f.submit "登録" %>

<% end %>
<%= link_to "戻る",top_main_path %>

dev/app/views/top/error.html.erb
Did not match.Please try again.</br>
<%= link_to "back","/" %>

dev/app/views/top/home.html.erb
<h1>Home</h1>
<h2>Products</h2>
<%= Product.delete_all %>
<%= Product.create! id: 1, name: "PlayStation 4", price: 30000, active: true %>
<%= Product.create! id: 2, name: "Nintendo Switch", price: 30000, active: true %> 
<%= Product.create! id: 3, name: "加湿器", price: 5000, active: true %>
<%= Product.create! id: 4, name: "掃除機", price: 8000, active: true %>

dev/app/views/top/login.html.erb
<h1>BATRE(バトレ)</h1>
<h2>sign-in</h2>
<%= form_tag '/top/login', method: :post do %>
  <%= label_tag :uid,'username' %><br>
  <%= text_field_tag :uid%><br>
  <%= label_tag :pass,'password' %><br>
  <%= password_field_tag :pass %>
  <%= submit_tag 'go' %>
<% end %>
<%= link_to 'create new account' , '/login/new' %>

dev/app/views/top/main.html.erb
<table border="1">

商品一覧


<tr>
    <th>商品名</th>
    <th>価格</th>
    <th>お気に入り</th>
    <th>削除</th>
</tr>

<% @products.each do |p| %>
  
  <tr>
      <td><%= p.name %></td>
      <td><%= p.price %></td>
      <td><%= link_to "お気に入り",item_index_path(id: p.id),method: :post %></td>
      <td><%= link_to "削除",product_path(p),method: :delete,data: {confirm: '削除してもいいですか？' } %></td>
  </tr>
  
<% end %>

</table>

<p>
    <%= link_to "お気に入り",trade_show_path %>
</p>

<p>
    <%= link_to "商品登録",new_product_path %>
</p>

dev/app/views/top/new.html.erb
<%= form_for @user,:url => {:action => :create} do |f| %>
<h1>New Account</h1>
  <%= label_tag :uid,'username' %><br>
  <%= text_field_tag :uid%><br>
  <%= label_tag :pass,'password' %><br>
  <%= password_field_tag :pass %>
  <%= label_tag ,'email address' %><br>
  
  <%= submit_tag 'create' %>
<% end %>

dev/app/views/trade/end.html.erb
<h1> 取引完了！ </h1>
<%= link_to "ホームに戻る",top_main_path %>

dev/app/views/trade/show.html.erb
<h1>取引画面</h1>
取引しますか？
<%= link_to "Yes" ,trade_end_path %>
<%= link_to "No",top_main_path %>

dev/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

dev/app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

dev/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

dev/app/views/user/new.html.erb
<%= form_for(@user) do |f| %>
 
  <div class="form-group">
    <%= f.label :nickname, 'ニックネーム' %>
    <%= f.text_field :nickname, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（もう１度入力してください）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
 
  <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
<% end %>

dev/app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

dev/app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>